# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: echo Hello, world! SysDir is $(System.DefaultWorkingDirectory)
  displayName: 'System Default Dir Checker'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/reports/jacoco/test/jacocoTestReport.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/reports/jacoco/test/html"
    failIfCoverageEmpty: true